### ISSUE TITLE
double \\

### ISSUE THREAD

**Issue by fanios** [qinyuanpei/Excel2Unity#3]
Hi,my excel content has some words like "Hello,\n Continue".After shifting, it comes "Hello,\\n Continue" in JSON files. However ,I need it has only one "\",what should I do ?

**Comment by qinyuanpei** [comment]
Please refer [http://json.org/](http://json.org/), I suggest to replace " to \" in Excel file.
```
var answer = "Please refer \"http://json.org\" to find your answer";
```
